packages:
  - name: leads
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SES_REGION: ${AWS_SES_REGION}
      LEAD_EMAIL_TO: ${LEAD_EMAIL_TO}
      LEAD_EMAIL_FROM: ${LEAD_EMAIL_FROM}
    functions:
      - name: contact
        runtime: nodejs:22
        web: raw
